kubectl delete deployment backend-user-deployment
kubectl delete services backend-user
kubectl delete deployment backend-feed-deployment
kubectl delete services backend-feed
kubectl delete deployment reverseproxy-deployment
kubectl delete services reverseproxy
kubectl delete services publicreverseproxy
kubectl delete deployment frontend-deployment
kubectl delete services frontend
kubectl delete services publicfrontend