kubectl delete deployment backend-user
kubectl delete services backend-user
kubectl delete deployment backend-feed
kubectl delete services backend-feed
kubectl delete deployment reverseproxy
kubectl delete services reverseproxy
kubectl delete services publicreverseproxy
kubectl delete deployment frontend
kubectl delete services frontend
kubectl delete services publicfrontend