version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Run set_env.sh
          command: source set_env.sh

      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install docker-compose

      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose-build.yaml build --parallel

      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker images
          command: |
            docker-compose -f docker-compose-build.yaml push

      - run:
          name: Run Docker containers
          command: docker-compose up -d

      - run:
          name: Verify running containers
          command: docker ps

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
