version: 2.1
 
jobs:
  build-and-push:
    docker:
      - image: docker:20.10
    steps:
      - setup_remote_docker:
          version: 20.10.23
      - checkout
      - run:
          name: Build Docker images using Docker Compose
          command: |
            docker-compose -f docker-compose-build.yaml build
      - run:
          name: Tag Docker images
          command: |
            docker tag reverseproxy levantienn/reverseproxy:latest
            docker tag udagram-api-user levantienn/udagram-api-user:latest
            docker tag udagram-api-feed levantienn/udagram-api-feed:latest
            docker tag udagram-frontend:local levantienn/udagram-frontend:latest
      - run:
          name: Login to DockerHub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker images to DockerHub
          command: |
            docker push levantienn/reverseproxy:latest
            docker push levantienn/udagram-api-user:latest
            docker push levantienn/udagram-api-feed:latest
            docker push levantienn/udagram-frontend:latest
 
workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push